export const ProductType = Object.freeze({
  BOOK: "BOOK",
  MANGA: "MANGA",
  COMIC: "COMIC",
});

export const categories = [
  { id: 1, name: "Realismo mágico" },
  { id: 2, name: "Clásico" },
  { id: 3, name: "Distopía" },
  { id: 4, name: "Fantasía" },
  { id: 5, name: "Aventura" },
  { id: 6, name: "Ciencia ficción" },
  { id: 7, name: "Novela gráfica" },
  { id: 8, name: "Superhéroes" },
  { id: 9, name: "Seinen" },
  { id: 10, name: "Terror" },
  { id: 11, name: "Romance" },
  { id: 12, name: "Shonen" },
  { id: 13, name: "Sátira" },
  { id: 14, name: "Policial negro" },
  { id: 15, name: "Infantil" },
  { id: 16, name: "Histórico" },
  { id: 17, name: "Suspenso" },
];


export const products = [
  // ---------- BOOKS ----------
  {
    id: 1,
    type: ProductType.BOOK,
    title: "Cien años de soledad",
    description: "Obra cumbre del realismo mágico que cuenta la mítica historia de la familia Buendía en el pueblo de Macondo.",
    author: "Gabriel García Márquez",
    isbn: "9780060883287",
    publicationDate: "1967-06-05",
    categoryIds: [1, 2],
    price: 18.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg",
  },
  {
    id: 2,
    type: ProductType.BOOK,
    title: "1984",
    description: "Una inquietante novela distópica sobre una sociedad vigilada por el 'Gran Hermano', donde el pensamiento libre es un crimen.",
    author: "George Orwell",
    isbn: "9780451524935",
    publicationDate: "1949-06-08",
    categoryIds: [3, 2],
    price: 12.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
  },
  {
    id: 7,
    type: ProductType.BOOK,
    title: "Don Quijote de la Mancha",
    description: "Las divertidas y trágicas aventuras de un hidalgo que, tras leer demasiadas novelas de caballería, decide convertirse en caballero andante.",
    author: "Miguel de Cervantes",
    isbn: "9780060934347",
    publicationDate: "1605-01-16",
    categoryIds: [2, 13],
    price: 15.50,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780060934347-L.jpg",
  },
  {
    id: 8,
    type: ProductType.BOOK,
    title: "El Principito",
    description: "Un cuento poético sobre un piloto perdido en el desierto que conoce a un pequeño príncipe de otro planeta.",
    author: "Antoine de Saint-Exupéry",
    isbn: "9780156012195",
    publicationDate: "1943-04-06",
    categoryIds: [15],
    price: 9.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780156012195-L.jpg",
  },
  {
    id: 9,
    type: ProductType.BOOK,
    title: "Orgullo y Prejuicio",
    description: "Un clásico de la literatura romántica que critica las convenciones sociales a través de la historia de Elizabeth Bennet y el señor Darcy.",
    author: "Jane Austen",
    isbn: "9780141439518",
    publicationDate: "1813-01-28",
    categoryIds: [11, 2],
    price: 11.20,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
  },
  {
    id: 10,
    type: ProductType.BOOK,
    title: "Harry Potter y la piedra filosofal",
    description: "El primer libro de la famosa saga donde un niño huérfano descubre que es mago y viaja al colegio Hogwarts.",
    author: "J.K. Rowling",
    isbn: "9780590353403",
    publicationDate: "1997-06-26",
    categoryIds: [4, 5],
    price: 16.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780590353403-L.jpg",
  },
  {
    id: 11,
    type: ProductType.BOOK,
    title: "El Señor de los Anillos: La Comunidad del Anillo",
    description: "El inicio del épico viaje en la Tierra Media para destruir el Anillo Único y detener al Señor Oscuro.",
    author: "J.R.R. Tolkien",
    isbn: "9780544003415",
    publicationDate: "1954-07-29",
    categoryIds: [4, 5],
    price: 22.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780544003415-L.jpg",
  },
  {
    id: 12,
    type: ProductType.BOOK,
    title: "El alquimista",
    description: "Una fábula espiritual sobre un joven pastor andaluz que viaja a Egipto en busca de su leyenda personal y un tesoro oculto.",
    author: "Paulo Coelho",
    isbn: "9780061122415",
    publicationDate: "1988-01-01",
    categoryIds: [5],
    price: 12.00,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg",
  },
  {
    id: 13,
    type: ProductType.BOOK,
    title: "Matar a un ruiseñor",
    description: "Una mirada a la injusticia racial en el sur de Estados Unidos contada desde los ojos de una niña inocente.",
    author: "Harper Lee",
    isbn: "9780060935467",
    publicationDate: "1960-07-11",
    categoryIds: [2],
    price: 14.50,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780060935467-L.jpg",
  },
  {
    id: 14,
    type: ProductType.BOOK,
    title: "El diario de Ana Frank",
    description: "El conmovedor testimonio real de una niña judía que vivió escondida con su familia durante la ocupación nazi.",
    author: "Ana Frank",
    isbn: "9780553296983",
    publicationDate: "1947-06-25",
    categoryIds: [16, 2],
    price: 10.50,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780553296983-L.jpg",
  },
  {
    id: 15,
    type: ProductType.BOOK,
    title: "Frankenstein",
    description: "La historia del doctor Victor Frankenstein, quien logra dar vida a una criatura formada por partes de cadáveres, desencadenando la tragedia.",
    author: "Mary Shelley",
    isbn: "9780486282114",
    publicationDate: "1818-01-01",
    categoryIds: [10, 6, 2],
    price: 11.00,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780486282114-L.jpg",
  },
  {
    id: 16,
    type: ProductType.BOOK,
    title: "Drácula",
    description: "La clásica novela epistolar que definió el mito moderno del vampiro, siguiendo al siniestro Conde desde Transilvania hasta Londres.",
    author: "Bram Stoker",
    isbn: "9780486411095",
    publicationDate: "1897-05-26",
    categoryIds: [10, 2],
    price: 13.20,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780486411095-L.jpg",
  },
  {
    id: 17,
    type: ProductType.BOOK,
    title: "Alicia en el país de las maravillas",
    description: "Un relato fantástico donde una niña cae por una madriguera de conejo y llega a un mundo absurdo lleno de criaturas extrañas.",
    author: "Lewis Carroll",
    isbn: "9780486275437",
    publicationDate: "1865-11-26",
    categoryIds: [15, 4],
    price: 9.50,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780486275437-L.jpg",
  },
  {
    id: 18,
    type: ProductType.BOOK,
    title: "Un mundo feliz",
    description: "Una visión futurista donde la sociedad está controlada mediante tecnología, condicionamiento genético y una droga para mantener la felicidad superficial.",
    author: "Aldous Huxley",
    isbn: "9780060850524",
    publicationDate: "1932-01-01",
    categoryIds: [3, 6],
    price: 14.00,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
  },
  {
    id: 19,
    type: ProductType.BOOK,
    title: "El gran Gatsby",
    description: "Un retrato de los locos años veinte, la decadencia, el exceso y el sueño americano a través del misterioso millonario Jay Gatsby.",
    author: "F. Scott Fitzgerald",
    isbn: "9780743273565",
    publicationDate: "1925-04-10",
    categoryIds: [2],
    price: 11.90,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
  },

  // ---------- MANGAS ----------
  {
    id: 3,
    type: ProductType.MANGA,
    title: "Berserk",
    description: "Berserk es un manga oscuro y violento que sigue la historia de Guts, un guerrero solitario que lucha contra fuerzas sobrenaturales en un mundo medieval lleno de demonios y corrupción.",
    author: "Kentaro Miura",
    isbn: "9781593070205",
    publicationDate: "1989-08-25",
    categoryIds: [9, 4],
    price: 10.99,
    available: true,
    imageUrl: "https://cdn.myanimelist.net/images/manga/1/157897l.jpg",
  },
  {
    id: 4,
    type: ProductType.MANGA,
    title: "One Piece",
    description: "One Piece es un manga de aventuras y fantasía que sigue las aventuras de Monkey D. Luffy y su tripulación de piratas en busca del tesoro legendario conocido como 'One Piece'.",
    author: "Eiichiro Oda",
    isbn: "9781569319017",
    publicationDate: "1997-07-22",
    categoryIds: [5, 4],
    price: 9.99,
    available: true,
    imageUrl: "https://cdn.myanimelist.net/images/manga/2/253146l.jpg",
  },
  {
    id: 6,
    type: ProductType.MANGA,
    title: "Tokyo Ghoul",
    description: "Tokyo Ghoul es un manga de horror y acción que sigue la historia de Ken Kaneki, un joven universitario que se convierte en mitad ghoul después de un accidente.",
    author: "Sui Ishida",
    isbn: "9781421580364",
    publicationDate: "2011-09-08",
    categoryIds: [9, 10],
    price: 13.99,
    available: true,
    imageUrl: "https://cdn.myanimelist.net/images/manga/3/114037l.jpg",
  },
  {
    id: 20,
    type: ProductType.MANGA,
    title: "JoJo no Kimyou na Bouken Part 7: Steel Ball Run",
    description: "Steel Ball Run es la séptima parte de la serie JoJo's Bizarre Adventure, que sigue las aventuras de Johnny Joestar y Gyro Zeppeli en una carrera a través de los Estados Unidos del siglo XIX, enfrentándose a enemigos y descubriendo misterios sobrenaturales.",
    author: "Hirohiko Araki",
    isbn: "9781974752546",
    publicationDate: "2004-01-19",
    categoryIds: [12, 5],
    price: 12.99,
    available: true,
    imageUrl: "https://cdn.myanimelist.net/images/manga/3/179882l.jpg",
  },
  {
    id: 21,
    type: ProductType.MANGA,
    title: "Vagabond",
    description: "Vagabond es un manga de acción y aventura que sigue la historia de Miyamoto Musashi, un samurái que busca perfeccionar su arte marcial y encontrar su lugar en el mundo.",
    author: "Takehiko Inoue",
    isbn: "9781421520544",
    publicationDate: "1998-09-17",
    categoryIds: [9, 5],
    price: 15.99,
    available: true,
    imageUrl: "https://cdn.myanimelist.net/images/manga/1/259070l.jpg",
  },
  {
    id: 22,
    type: ProductType.MANGA,
    title: "Fullmetal Alchemist",
    description: "Fullmetal Alchemist es un manga de fantasía y aventura que sigue la historia de los hermanos Edward y Alphonse Elric, quienes buscan la Piedra Filosofal para restaurar sus cuerpos después de un fallido experimento de alquimia.",
    author: "Hiromu Arakawa",
    isbn: "9781591169208",
    publicationDate: "2001-07-12",
    categoryIds: [12, 4],
    price: 11.99,
    available: true,
    imageUrl: "https://cdn.myanimelist.net/images/manga/3/243675l.jpg",
  },
  {
    id: 23,
    type: ProductType.MANGA,
    title: "Hunter x Hunter",
    description: "Hunter x Hunter es un manga de acción y aventura que sigue la historia de Gon Freecss, un joven que se convierte en cazador para encontrar a su padre y enfrentarse a desafíos peligrosos en un mundo lleno de criaturas y habilidades especiales.",
    author: "Yoshihiro Togashi",
    isbn: "9781591167532",
    publicationDate: "1998-03-03",
    categoryIds: [12, 5],
    price: 10.99,
    available: true,
    imageUrl: "https://cdn.myanimelist.net/images/manga/2/253119l.jpg",
  },
  {
    id: 24,
    type: ProductType.MANGA,
    title: "Death Note",
    description: "Death Note es un manga de suspenso y misterio que sigue la historia de Light Yagami, un estudiante que encuentra un cuaderno con el poder de matar a cualquier persona cuyo nombre escriba en él, y su enfrentamiento con el detective L.",
    author: "Tsugumi Ohba",
    isbn: "9781421501680",
    publicationDate: "2003-12-01",
    categoryIds: [12, 17],
    price: 12.99,
    available: true,
    imageUrl: "https://cdn.myanimelist.net/images/manga/1/258245l.jpg",
  },
  {
    id: 25,
    type: ProductType.MANGA,
    title: "Akira",
    description: "Akira es un manga de ciencia ficción y acción que se desarrolla en un futuro post-apocalíptico en Neo-Tokio, donde un joven llamado Kaneda se ve envuelto en una conspiración gubernamental y descubre los secretos de un niño con poderes psíquicos llamados Akira.",
    author: "Katsuhiro Otomo",
    isbn: "9781569714980",
    publicationDate: "1982-12-20",
    categoryIds: [9, 6],
    price: 14.99,
    available: true,
    imageUrl: "https://cdn.myanimelist.net/images/manga/3/271629l.jpg",
  },

  // ---------- COMICS ----------
  {
    id: 5,
    type: ProductType.COMIC,
    title: "Watchmen",
    description: "Una obra maestra que deconstruye el género de superhéroes en un mundo al borde de la guerra nuclear.",
    author: "Alan Moore & Dave Gibbons",
    isbn: "9780930289232",
    publicationDate: "1986-09-01",
    categoryIds: [7, 8],
    price: 19.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780930289232-L.jpg",
  },
  {
    id: 26,
    type: ProductType.COMIC,
    title: "Batman: El regreso del Caballero Oscuro",
    description: "Un Bruce Wayne envejecido y amargado vuelve a ponerse la capa para salvar a una Ciudad Gótica sumida en el caos.",
    author: "Frank Miller",
    isbn: "9781563893421",
    publicationDate: "1986-02-01",
    categoryIds: [8, 7],
    price: 15.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9781563893421-L.jpg",
  },
  {
    id: 27,
    type: ProductType.COMIC,
    title: "Batman: La broma asesina",
    description: "Explora el oscuro origen psicológico del Joker y su intento de demostrar que cualquiera puede enloquecer con 'un mal día'.",
    author: "Alan Moore & Brian Bolland",
    isbn: "9781401216672",
    publicationDate: "1988-03-01",
    categoryIds: [8, 7],
    price: 14.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9781401216672-L.jpg",
  },
  {
    id: 28,
    type: ProductType.COMIC,
    title: "V de Vendetta",
    description: "En una Inglaterra fascista y distópica, un misterioso y teatral anarquista enmascarado busca derrocar al gobierno.",
    author: "Alan Moore & David Lloyd",
    isbn: "9780930289522",
    publicationDate: "1982-03-01",
    categoryIds: [3, 7],
    price: 18.50,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780930289522-L.jpg",
  },
  {
    id: 29,
    type: ProductType.COMIC,
    title: "The Sandman: Preludios y Nocturnos",
    description: "Morfeo, el Rey de los Sueños, escapa de su cautiverio de décadas y emprende un viaje para recuperar sus objetos de poder.",
    author: "Neil Gaiman",
    isbn: "9781401225759",
    publicationDate: "1989-01-01",
    categoryIds: [4, 7],
    price: 19.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9781401225759-L.jpg",
  },
  {
    id: 30,
    type: ProductType.COMIC,
    title: "Saga, Vol. 1",
    description: "Una épica odisea espacial de fantasía que sigue a dos soldados de especies enemigas que se enamoran y tratan de proteger a su hija.",
    author: "Brian K. Vaughan & Fiona Staples",
    isbn: "9781607066019",
    publicationDate: "2012-10-23",
    categoryIds: [6, 4],
    price: 9.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9781607066019-L.jpg",
  },
  {
    id: 31,
    type: ProductType.COMIC,
    title: "The Walking Dead, Vol. 1",
    description: "El oficial de policía Rick Grimes despierta de un coma en un hospital abandonado para encontrar un mundo invadido por muertos vivientes.",
    author: "Robert Kirkman",
    isbn: "9781582406725",
    publicationDate: "2004-05-12",
    categoryIds: [10, 7],
    price: 14.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9781582406725-L.jpg",
  },
  {
    id: 32,
    type: ProductType.COMIC,
    title: "Civil War (Marvel)",
    description: "El universo Marvel se divide en dos bandos cuando el gobierno exige que todos los superhéroes revelen sus identidades y se registren.",
    author: "Mark Millar & Steve McNiven",
    isbn: "9780785121794",
    publicationDate: "2006-07-01",
    categoryIds: [8, 7],
    price: 24.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780785121794-L.jpg",
  },
  {
    id: 33,
    type: ProductType.COMIC,
    title: "Persépolis",
    description: "Una novela gráfica autobiográfica que retrata la infancia y juventud de la autora en Irán, antes y después de la Revolución Islámica.",
    author: "Marjane Satrapi",
    isbn: "9780375714573",
    publicationDate: "2000-01-01",
    categoryIds: [7, 16],
    price: 16.95,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780375714573-L.jpg",
  },
  {
    id: 34,
    type: ProductType.COMIC,
    title: "Sin City: El duro adiós",
    description: "Un relato de novela negra crudo y violento ambientado en Basin City, siguiendo a Marv en su sangrienta búsqueda de venganza.",
    author: "Frank Miller",
    isbn: "9781593072933",
    publicationDate: "1992-04-01",
    categoryIds: [14, 7],
    price: 17.50,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9781593072933-L.jpg",
  },
  {
    id: 35,
    type: ProductType.COMIC,
    title: "Hellboy: Semilla de destrucción",
    description: "El oscuro origen del demonio convertido en investigador paranormal que lucha contra fuerzas ocultas, nazis y monstruos lovecraftianos.",
    author: "Mike Mignola",
    isbn: "9781593070946",
    publicationDate: "1994-03-01",
    categoryIds: [10, 4],
    price: 15.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9781593070946-L.jpg",
  },
  {
    id: 36,
    type: ProductType.COMIC,
    title: "Astérix el Galo",
    description: "Las incombustibles aventuras de una aldea de irreductibles galos que resisten la invasión del Imperio Romano gracias a una poción mágica.",
    author: "René Goscinny & Albert Uderzo",
    isbn: "9780752866055",
    publicationDate: "1961-07-01",
    categoryIds: [13, 5],
    price: 12.99,
    available: true,
    imageUrl: "https://covers.openlibrary.org/b/isbn/9780752866055-L.jpg",
  },
];


export const productsById = new Map(products.map((p) => [p.id, p]));
export const categoriesById = new Map(categories.map((c) => [c.id, c]));


export function getProductById(id) {
  return productsById.get(id);
}


export function getProductsByType(type) {
  return products.filter((p) => p.type === type);
}

export function getCategoriesForProduct(productId) {
  const product = productsById.get(productId);
  if (!product) return [];
  return product.categoryIds
    .map((id) => categoriesById.get(id))
    .filter(Boolean);
}

export function searchProductsByTitle(query) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [];

  return products.filter((p) => {
    // Busca estrictamente por la inicial/comienzo del título completo
    return p.title.toLowerCase().startsWith(normalized);
  });
}